### PR TITLE
Updating README

### PR DESCRIPTION
**Pull request by stursby**
README now has a Quick Start guide to help people get Vino running

### CODE REVIEW

**Comment by siavashg** [comment]
Great, thanks!

**Comment by DerrickLamers** [comment]
It appears the API no longer functions.

  File "/vine/vino/vine.py", line 53, in _call
    return r.json()
TypeError: 'dict' object is not callable

**Comment by stursby** [comment]
Hey Derrick,

I'm not able to recreate that error. I cloned a fresh repo and
followed the Quick
Start https://github.com/starlock/vino#quick-start guide and it worked
just fine for me.

Could you provide some more info?

Like what OS you're on, Python version, do you have PIP installed?

_charlie

**Comment by hult** [comment]
I can't reproduce it either, @derricklamers. Seems like r.json is a dict for you, which it isn't supposed to be.

**Comment by DerrickLamers** [comment]
Well, I thought maybe it was because I'm using it on OSX but it appears the root problem lies in the requirements.txt file. Flask fails to install and pylibmc fails to install. I have tried on both Ubuntu and OSX and get all kinds of errors.

**Comment by hult** [comment]
I use OS X myself (haven't tried installing anywhere else). Flask should have no external dependencies and should install on all systems. Pylibmc depends on libmemcached, I'll clarify that in the README.

Could this be a permission issue? You're going to need write permissions where pip is going to write. If you're not using virtualenv, that probably means that you need to be root (i.e. run `sudo pip install -r requirements.txt`).

**Pull request merged**
